version: "3.8"

services:
  backend:
    image: sensors-backend
    build:
      context: ./back
      dockerfile: Dockerfile

    ports:
      - 4200:80
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile

    ports:
      - 3000:4200
    
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4200
    
    depends_on:
      - backend
